### ISSUE TITLE
Use standard log crate

### ISSUE THREAD

**Issue by aburd** [bvanseg/ccake#15]
**Is your feature request related to a problem? Please describe.**

Consider using a community standard logging facade: https://crates.io/crates/log
Rather than the implementation we have src/terminal/ansi.rs

**Describe the solution you'd like**

- A logging solution which is accessible
  - Everything uses this and changing the log level will be helpful for any dependency troubleshooting

**Describe alternatives you've considered**
None as of now

**Additional context**

**Comment by wildernessems** [comment]
`fix/standard_logging` is ready to push once added as a contributor.
