### ISSUE TITLE
Use GitHub Actions to run unit tests on push instead of locking down commits

### ISSUE THREAD

**Issue by wildernessems** [bvanseg/ccake#18]
**Is your feature request related to a problem? Please describe.**
Locking down commits with [/hooks/pre-commit](https://github.com/bvanseg/ccake/blob/master/hooks/pre-commit) makes version control and collaboration more difficult.

**Describe the solution you'd like**
Use GitHub Actions and unit tests to ensure functionality instead.

**Comment by aburd** [comment]
Agreed. Doing all the CI with PRs should be enough. Especially when you're just working on a branch by yourself, it's not necessary to check on every commit.
