### ISSUE TITLE
Use `dialoguer` instead of rolling your own interaction system

### ISSUE THREAD

**Issue by wildernessems** [bvanseg/ccake#19]
**Is your feature request related to a problem? Please describe.**
The functionality in [/src/lib/terminal/prompt.rs](https://github.com/bvanseg/ccake/blob/master/src/lib/terminal/prompt.rs) would be better served by the [dialoguer](https://docs.rs/dialoguer/latest/dialoguer/index.html) crate.

**Describe the solution you'd like**
Use the premade solution instead.

**Describe alternatives you've considered**
I tried rolling my own input system when I started writing Rust and it grew tangled and messy as scope expanded. I don't advise it.

**Comment by bvanseg** [comment]
@wildernessems If you do not yet have a branch or PR for this, I'd be happy to take it on.
