### ISSUE TITLE
Install script aliasing

### ISSUE THREAD

**Issue by bvanseg** [bvanseg/ccake#4]
**Is your feature request related to a problem? Please describe.**
If a user wants to install gcc on Windows, they currently have to run `ccake install mingw`. There are a couple problems with this. MinGW will not be necessary on linux machines, as gcc should be the native toolchain. A linux user should therefore not be expected to run `ccake install mingw`, but `ccake install gcc` instead. Ideally, both windows and linux users should have to type the same thing, which should be `ccake install gcc`.

**Describe the solution you'd like**
If a Windows user types `ccake install gcc`, CCake should really treat the identifier `gcc` as `mingw`, but only on Windows.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by aburd** [comment]
Doing
